package com.xalidmuslim.arabicgrammar.ui

import androidx.activity.compose.BackHandler
import androidx.compose.animation.*
import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.tween
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveableStateHolder
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.xalidmuslim.arabicgrammar.data.BookRepository
import com.xalidmuslim.arabicgrammar.data.ProgressStore

sealed interface Screen { data object Home:Screen; data class Library(val chapter:String?=null):Screen; data class Reader(val sectionId:String):Screen; data object Practice:Screen; data class Quiz(val reviewErrors:Boolean=false):Screen; data class Flashcards(val reviewOnly:Boolean=false):Screen; data class ConjugationTrainer(val reviewOnly:Boolean=false):Screen; data object Search:Screen; data object Settings:Screen; data object Bookmarks:Screen; data object Proverbs:Screen }
private fun screenStateKey(s:Screen)=when(s){Screen.Home->"home";is Screen.Library->"library:${s.chapter?:"root"}";is Screen.Reader->"reader:${s.sectionId}";Screen.Practice->"practice";is Screen.Quiz->"quiz:${s.reviewErrors}";is Screen.Flashcards->"flashcards:${s.reviewOnly}";is Screen.ConjugationTrainer->"conjugation:${s.reviewOnly}";Screen.Search->"search";Screen.Settings->"settings";Screen.Bookmarks->"bookmarks";Screen.Proverbs->"proverbs"}
@Composable fun ArabicGrammarApp(repository:BookRepository,progress:ProgressStore){val settings=progress.settings;val stack=remember{mutableStateListOf<Screen>(Screen.Home)};var reverse by remember{mutableStateOf(false)};val holder=rememberSaveableStateHolder();val current=stack.last();DisposableEffect(repository){onDispose{repository.close()}};fun nav(s:Screen){if(stack.lastOrNull()!=s){reverse=false;stack.add(s)}};fun back(){if(stack.size>1){reverse=true;stack.removeAt(stack.lastIndex)}};fun top(s:Screen){reverse=false;if(s==Screen.Home){stack.clear();stack.add(Screen.Home);return};if(stack.firstOrNull()!=Screen.Home){stack.clear();stack.add(Screen.Home)};if(stack.lastOrNull()!=s)stack.add(s)};BackHandler(true){if(stack.size>1)back()};ArabicGrammarTheme(settings,isSystemInDarkTheme()){Scaffold(containerColor=MaterialTheme.colorScheme.background,bottomBar={AppBottomBar(current,::top)}){padding->AnimatedContent(targetState=current,modifier=Modifier.fillMaxSize().padding(padding),transitionSpec={if(settings.animations){val smooth=CubicBezierEasing(.2f,.86f,.2f,1f);if(reverse)(slideInHorizontally(tween(180,easing=smooth)){-it/26}+fadeIn(tween(150,easing=smooth))) togetherWith (slideOutHorizontally(tween(130,easing=smooth)){it/34}+fadeOut(tween(105,easing=smooth))) else (slideInHorizontally(tween(200,easing=smooth)){it/26}+fadeIn(tween(165,easing=smooth))) togetherWith (slideOutHorizontally(tween(140,easing=smooth)){-it/34}+fadeOut(tween(115,easing=smooth)))} else fadeIn(tween(1)) togetherWith fadeOut(tween(1))},label="screen"){screen->holder.SaveableStateProvider(screenStateKey(screen)){when(screen){Screen.Home->HomeScreen(repository,progress,::nav);is Screen.Library->LibraryScreen(repository,progress,screen.chapter,::nav,::back);is Screen.Reader->ReaderScreen(repository,progress,screen.sectionId,::nav,::back);Screen.Practice->PracticeScreen(repository,progress,::nav);is Screen.Quiz->QuizScreen(repository,progress,screen.reviewErrors,::back);is Screen.Flashcards->FlashcardsScreen(repository,progress,screen.reviewOnly,::back);is Screen.ConjugationTrainer->ConjugationTrainerScreen(repository,progress,screen.reviewOnly,::back);Screen.Search->SearchScreen(repository,progress,::nav);Screen.Settings->SettingsScreen(progress);Screen.Bookmarks->BookmarksScreen(repository,progress,::nav,::back);Screen.Proverbs->ProverbsScreen(repository,progress,::nav,::back)}}}}}}
@Composable private fun AppBottomBar(current:Screen,navigate:(Screen)->Unit){val items=listOf(Triple(Screen.Home as Screen,"Главная",Icons.Default.Home),Triple(Screen.Library() as Screen,"Книга",Icons.Default.MenuBook),Triple(Screen.Practice as Screen,"Практика",Icons.Default.School),Triple(Screen.Search as Screen,"Поиск",Icons.Default.Search),Triple(Screen.Settings as Screen,"Настройки",Icons.Default.Settings));Surface(modifier=Modifier.fillMaxWidth().navigationBarsPadding().padding(horizontal=10.dp,vertical=4.dp),shape=RoundedCornerShape(24.dp),color=MaterialTheme.colorScheme.surfaceContainer,tonalElevation=2.dp){NavigationBar(modifier=Modifier.height(64.dp),containerColor=Color.Transparent,tonalElevation=0.dp,windowInsets=WindowInsets(0,0,0,0)){items.forEach{(screen,label,icon)->val selected=when(screen){Screen.Home->current is Screen.Home;is Screen.Library->current is Screen.Library||current is Screen.Reader||current is Screen.Bookmarks||current is Screen.Proverbs;Screen.Practice->current is Screen.Practice||current is Screen.Quiz||current is Screen.Flashcards||current is Screen.ConjugationTrainer;Screen.Search->current is Screen.Search;Screen.Settings->current is Screen.Settings;else->false};NavigationBarItem(selected=selected,onClick={navigate(screen)},icon={Icon(icon,label)},label={Text(label,maxLines=1)},colors=NavigationBarItemDefaults.colors(selectedIconColor=MaterialTheme.colorScheme.primary,selectedTextColor=MaterialTheme.colorScheme.secondary,indicatorColor=NestedSageStrong,unselectedIconColor=MaterialTheme.colorScheme.onSurfaceVariant,unselectedTextColor=MaterialTheme.colorScheme.onSurfaceVariant))}}}}
